### ISSUE TITLE
Celeste crashes on Bullseye

### ISSUE THREAD

**Issue by AndusDEV** [daniel-j/fnalibs-celeste#5]
For some reason Celeste worked fine on RPiOS Buster but crashes after EXOK logo on Bullseye. Why?

**Comment by AndusDEV** [comment]
Here's the log:

```
performance
CELESTE : 1.4.0.0
Using EXT_swap_control_tear VSync!
FNA3D Driver: OpenGL
OpenGL Renderer: V3D 4.2
OpenGL Driver: 2.1 Mesa 20.3.5
OpenGL Vendor: Broadcom
MojoShader Profile: glsl120
BEGIN LOAD
 - GFX LOAD: 2660ms
 - MTN LOAD: 1668ms
Using EXT_swap_control_tear VSync!
FULLSCREEN
GAME DISPLAYED (in 4845ms)

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	 (No frames) 


=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0xf4fa6440 from 0xc3ea3440
Pkilling 0xf7afa040 from 0xc3ea3440
Entering thread summarizer pause from 0xc3ea3440
Finished thread summarizer pause from 0xc3ea3440.

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 1436]
[New LWP 1437]
[New LWP 1439]
[New LWP 1440]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
0xf792e568 in ioctl () at ../sysdeps/unix/syscall-template.S:120
120	../sysdeps/unix/syscall-template.S: Nie ma takiego pliku ani katalogu.
  Id   Target Id                                   Frame 
* 1    Thread 0xf7afa040 (LWP 1429) "mono"         0xf792e568 in ioctl () at ../sysdeps/unix/syscall-template.S:120
  2    Thread 0xf6bff440 (LWP 1436) "SGen worker"  futex_wait_cancelable (private=0, expected=0, futex_word=0x44769c) at ../sysdeps/nptl/futex-internal.h:186
  3    Thread 0xf4fa6440 (LWP 1437) "Finalizer"    futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=1, futex_word=0x43f73c) at ../sysdeps/nptl/futex-internal.h:323
  4    Thread 0xc3ea3440 (LWP 1439) "GAME_LOADER"  0xf78fd854 in __GI___wait4 (pid=1444, stat_loc=0xc3ea1a28, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
  5    Thread 0xb38ce440 (LWP 1440) "PulseHotplug" 0xf792bca8 in __GI___ppoll64 (fds=0xc3c0db80, nfds=3, timeout=0x0, sigmask=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:47

Thread 5 (Thread 0xb38ce440 (LWP 1440) "PulseHotplug"):
#0  0xf792bca8 in __GI___ppoll64 (fds=0xc3c0db80, nfds=3, timeout=0x0, sigmask=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:47
#1  0xf792be04 in __ppoll (fds=<optimized out>, nfds=<optimized out>, timeout=<optimized out>, sigmask=<optimized out>) at ../sysdeps/unix/sysv/linux/ppoll.c:78
#2  0xc3d31ef8 in pa_mainloop_poll () from /lib/arm-linux-gnueabihf/libpulse.so.0
#3  0xc3d3263c in pa_mainloop_iterate () from /lib/arm-linux-gnueabihf/libpulse.so.0
#4  0xc3d32710 in pa_mainloop_run () from /lib/arm-linux-gnueabihf/libpulse.so.0
#5  0xf482a170 in HotplugThread (data=data@entry=0x0) at /home/pi/fnalibs-celeste/lib/SDL/src/audio/pulseaudio/SDL_pulseaudio.c:799
#6  0xf47d4e10 in SDL_RunThread (thread=0xc3c16940) at /home/pi/fnalibs-celeste/lib/SDL/src/thread/SDL_thread.c:275
#7  0xf485330c in RunThread (data=<optimized out>) at /home/pi/fnalibs-celeste/lib/SDL/src/thread/pthread/SDL_systhread.c:77
#8  0xf79e1310 in start_thread (arg=0xb38ce440) at pthread_create.c:477
#9  0xf79365c8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 0xc3ea3440 (LWP 1439) "GAME_LOADER"):
#0  0xf78fd854 in __GI___wait4 (pid=1444, stat_loc=0xc3ea1a28, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x0009f73c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0xf4fa6440 (LWP 1437) "Finalizer"):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=1, futex_word=0x43f73c) at ../sysdeps/nptl/futex-internal.h:323
#1  do_futex_wait (sem=sem@entry=0x43f73c, abstime=0x0, clockid=0) at sem_waitcommon.c:117
#2  0xf79ecc90 in __new_sem_wait_slow (sem=0x43f73c, abstime=0x0, clockid=0) at sem_waitcommon.c:285
#3  0x002c2120 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0xf6bff440 (LWP 1436) "SGen worker"):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x44769c) at ../sysdeps/nptl/futex-internal.h:186
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7, cond=0x447670) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x447670, mutex=0x7) at pthread_cond_wait.c:638
#3  0x00327c84 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0xf7afa040 (LWP 1429) "mono"):
#0  0xf792e568 in ioctl () at ../sysdeps/unix/syscall-template.S:120
#1  0xf3d25c5c in drmIoctl () from /lib/arm-linux-gnueabihf/libdrm.so.2
#2  0xf3d2ab70 in drmSyncobjWait () from /lib/arm-linux-gnueabihf/libdrm.so.2
#3  0xf3575968 in ?? () from /usr/lib/arm-linux-gnueabihf/dri/vc4_dri.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
[Inferior 1 (process 1429) detached]

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0xc3d909a8):0xc3d90998  48 17 01 00 d0 ff ff ea 10 40 2d e9 00 40 90 e5  H........@-..@..
0xc3d909a8  00 00 94 e5 82 ff ff eb 04 00 a0 e1 9e ff ff eb  ................
0xc3d909b8  00 00 a0 e3 10 80 bd e8 00 30 90 e5 10 40 2d e9  .........0...@-.
0xc3d909c8  01 10 a0 e3 00 00 93 e5 8b ff ff eb 00 00 a0 e3  ................

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at FMOD.Studio.System:FMOD_Studio_System_Initialize <0x0004b>
	  at FMOD.Studio.System:initialize <0x00047>
	  at Celeste.Audio:Init <0x000ff>
	  at Celeste.GameLoader:LoadThread <0x00027>
	  at Celeste.RunThread:RunThreadWithLogging <0x00033>
	  at <>c__DisplayClass1_0:<Start>b__0 <0x0001b>
	  at System.Threading.ThreadHelper:ThreadStart_Context <0x000df>
	  at System.Threading.ExecutionContext:RunInternal <0x00203>
	  at System.Threading.ExecutionContext:Run <0x0002b>
	  at System.Threading.ExecutionContext:Run <0x00067>
	  at System.Threading.ThreadHelper:ThreadStart <0x00047>
	  at System.Object:runtime_invoke_void__this__ <0x000eb>
=================================================================
Przerwane
```
